name: Christophior
description: just blogging about stuff
meta_description: "Christophior's blog"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://blog.christophior.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'christophior'

# Details for the RSS feed generator
url:            'http://blog.christophior.com'
author:         'christophior'
authorTwitter:  'christophior'

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
